### ISSUE TITLE
Fixed title

### ISSUE THREAD

**Issue by mukheshpugal** [aklsh/startpage#1]
The page looks super cool. But the title is fixed as aklsh. Could it be made to adapt dynamically to any user?<br/>
Also, please include a way to add favourites without having to edit the html.<br/>
Thanks.

**Comment by aklsh** [comment]
I just whipped up some html and css specific to my setup. I am not really good at creating dynamic pages, neither do I want to for such a simple thing like a startpage, which I either use for search, or click on one of my favourite sites. If you want to make it match your setup, please edit to your liking. Dynamic pages slow down the load time of the start page, something that I don't want.

**Comment by aklsh** [comment]
alright! closing this...
