### ISSUE TITLE
Additional features

### ISSUE THREAD

**Issue by mukheshpugal** [aklsh/startpage#2]
There is a lot of empty space below the search bar. It would be nice to have additional features like a calculator, or a quick note.

**Comment by aklsh** [comment]
Again, this is all I want in *my startpage*. Plus, I'm not proficient in JS to build a calculator/notes app, even if I would use it.

**Comment by mukheshpugal** [comment]
I have forked the repo and I am working on this. I'll let you know once done.

**Comment by aklsh** [comment]
Cool! I'll maintain a separate branch for such widgets?

**Comment by mukheshpugal** [comment]
Sure!

**Comment by mukheshpugal** [comment]
Haven't finished fully yet, but try [this](https://github.com/mukheshpugal/startpage) out.

**Comment by aklsh** [comment]
Looks good. One thing that I can think of is using key-bindings like `<C-s>` for save, `i` for edit and so on. I'll try to incorporate that in it and maintain in a separate branch - "widgets"

**Comment by mukheshpugal** [comment]
Great! All the markdown-HTML conversions happen in `frame.html`. Any ideas on how to store note data into a file?

**Comment by mukheshpugal** [comment]
Make a new branch and I'll start a PR
